PRN292Project/PRN292Project/Controllers/HomeController.cs
using PRN292Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRN292Project.Controllers
{   [Authorize]
    public class HomeController : Controller
    {

        private PRN292_Project _db;
        public HomeController()
        {
            _db = new PRN292_Project();
        }
        public ActionResult Index()
        {
            var temp = _db.SinhViens.Select(x=>x).ToList();
            TempData["MonHoc"] = _db.MonHocs.Select(x => x).ToList();
            TempData["News"] = _db.News.Select(x => x).ToList();
            return View(temp);
        }

        public ActionResult IndexMonHoc()
        {
         
            var temp = _db.MonHocs.Select(x => x).ToList();
            return View(temp);
        }

        public ActionResult Test(string id)
        {
            var temp = _db.SinhViens.Where(x => x.MaSV == id).SingleOrDefault();
            return View(temp);
        }

        public ActionResult AddStudent(String id)
        {
            var temp = _db.MonHocs.Where(x => x.MaMH == id).SingleOrDefault();
            return View(temp);
        }
    }
}

PRN292Project/PRN292Project/Controllers/WidgetsController.cs
using PRN292Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRN292Project.Controllers
{
    public class WidgetsController : Controller
    {
        // GET: Widgets
        private readonly PRN292_Project _db;
        public WidgetsController()
        {
            _db = new PRN292_Project();
        }
        public PartialViewResult WidgetsPartial()
        {
            ViewBag.TongHocSinh = _db.SinhViens.Count();
            ViewBag.TongMonHoc = _db.MonHocs.Count();
            ViewBag.TongBaiViet = _db.News.Count();
            ViewBag.TongAbsent = _db.DiemDanhs.Where(x => x.DiemDanh1 == false).Count();
            return PartialView();
            
        }
    }
}

PRN292Project/PRN292Project/Views/Home/Footer.cshtml
<footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                Copyright &copy; 2018 Ela Admin
            </div>
            <div class="col-sm-6 text-right">
                Designed by <a href="https://colorlib.com">Colorlib</a>
            </div>
        </div>
    </div>
</footer>

PRN292Project/PRN292Project/Views/Home/Header.cshtml
<header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
            <a class="navbar-brand" href="./"><img src="images/logo.png" alt="Logo"></a>
            <a class="navbar-brand hidden" href="./"><img src="images/logo2.png" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div>

                <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">3</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                    </div>
                </div>

                <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                        <span class="count bg-primary">4</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jonathan Smith</span>
                                <span class="time float-right">Just now</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jack Sanders</span>
                                <span class="time float-right">5 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Cheryl Wheeler</span>
                                <span class="time float-right">10 minutes ago</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Rachel Santos</span>
                                <span class="time float-right">15 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="images/admin.jpg" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                    <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                    <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                    <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                </div>
            </div>

        </div>
    </div>
</header>

PRN292Project/PRN292Project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var monhoc = (List<Project_PRN292.Models.MonHoc>)TempData["MonHoc"];
    var news = (List<Project_PRN292.Models.News>)TempData["News"];
}
@model List<Project_PRN292.Models.SinhVien>

<div class="animated fadeIn">
    @Html.Action("WidgetsPartial", "Widgets")
    <div class="row">
        <div class="col-lg-5">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">News</strong>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table1" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in news)
                                    {
                                        <tr class=" pb-0">

                                            <td>@Html.ActionLink(item.Title, "", "", new { id = item.ID }, null) </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-7">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Danh sách tiếng việt</strong>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table2" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Ma Mon Hoc</th>
                                        <th>Ten Mon Hoc</th>
                                        <th>Option</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in monhoc)
                                    {
                                        <tr class=" pb-0">
                                            <td>@item.MaMH</td>
                                            <td>@item.TenMH</td>
                                            <td>
                                                <input type="button" class="btn btn-primary" data-toggle="modal" data-target="#Register" value="Register" onclick="return editSinhVien('@item.MaMH')" />
                                            </td>
                                            
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Danh sách tiếng việt</strong>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>MaSV</th>
                                        <th>Ten</th>
                                        <th>Ngay Sinh</th>
                                        <th>Gioi tinh</th>
                                        <th>Email</th>
                                        <th>Option</th>
                                        <th>Option</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.MaSV</td>
                                            <td>@item.Ten</td>
                                            <td>@item.NgaySinh</td>
                                            @if (item.GioiTinh.Value)
                                            {
                                                <td>Nam</td>
                                            }
                                            else
                                            {
                                                <td>Nữ</td>
                                            }
                                            <td>@item.Email</td>

                                            <td>
                                                <input type="button" class="btn btn-success" data-toggle="modal" data-target="#Editmodal" value="Edit" onclick="return editSinhVien('@item.MaSV')" />
                                            </td>
                                            <td>
                                                @Html.ActionLink("Delete", "Test", "Home", new { id = item.MaSV }, new { @class = "btn btn-success" })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Editmodal" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sửa thông tin sinh viên</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Tên học sinh:</label>
                        <input type="text" class="form-control" id="studentName" value="" required>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Ngày sinh:</label>
                        <input type="text" class="form-control" id="doblast" readonly>
                        <input type="date" class="form-control" id="dob">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Giới Tính:</label><br />
                        <input type='radio' name='gender' value='Male'>Nam <br />
                        <input type='radio' name='gender' value='Female'>Nữ <br />
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Email:</label>
                        <input type="text" class="form-control" id="email" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Register" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm sinh viên vào lớp</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Mã số sinh viên:</label>
                        <input type="text" class="form-control" id="studentName" value="" required>
                    </div>
                    
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Ok</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script src="~/Content/assets/js/indexBody.js"></script>
}

PRN292Project/PRN292Project/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Project_PRN292.Models.SinhVien
<h2>@Model.Email</h2>